### ISSUE TITLE
updating the Funny System again (1.2.0)

### ISSUE THREAD

**Issue by RealOrbital32** [ow-mods/ow-mod-db#442]
### Your Discord Name

(no need to do this anymore)

### Mod uniqueName

O32.FunnySystem

### Mod name

The Funniest System

### GitHub repository URL

https://github.com/RealOrbital32/funny-system

### Author display name

Orbital 32 (a.k.a. cigtu)

### Parent uniqueName

xen.NewHorizons

**Comment by RealOrbital32** [comment]
1. and yes, i did update the version number, so i'm 90% sure you can close that merge thing
2. is there a more effecient way to ask to update a mod?

**Comment by xen-42** [comment]
Will update automatically, no need for an issue
