### ISSUE TITLE
N Body Chaos

### ISSUE THREAD

**Issue by adrisj7** [ow-mods/ow-mod-db#511]
### Your Discord Name

TacoTechnica#6235

### Mod uniqueName

TacoTechnica.NBodyChaos

### Mod name

N Body Chaos

### GitHub repository URL

https://github.com/adrisj7/OW_NBodyChaos

### Tags

gameplay, tweaks

### Author display name

TacoTechnica

**Comment by MegaPiggy** [comment]
Needs a release
https://github.com/adrisj7/OW_NBodyChaos/releases

**Comment by Raicuparta** [comment]
Well
