### ISSUE TITLE
No Dot Mod

### ISSUE THREAD

**Issue by hearth1an** [ow-mods/ow-mod-db#564]
### Your Discord Name

hearth1an#7222 

### Mod uniqueName

hearth1an.NoDotMod

### Mod name

No Dot Mod

### GitHub repository URL

https://github.com/hearth1an/NoDotMod

### Tags

tweaks

### Author display name

hearth1an

### Parent uniqueName

hearth1an.NoDotMod

### Utility mod

Is utility

### Alpha Mod

None

**Comment by MegaPiggy** [comment]
Why does it use New Horizons?

**Comment by hearth1an** [comment]
Idk maybe it was added as accident
