### ISSUE TITLE
SbekuMod

### ISSUE THREAD

**Issue by CorsDev** [ow-mods/ow-mod-db#569]
### Your Discord Name

LaStringa#1693

### Mod uniqueName

LaStringa.SbekuMod

### Mod name

SbekuMod

### GitHub repository URL

https://github.com/SbekuMod/mod

### Tags

gameplay, content

### Author display name

LaStringa & SOWCT

### Utility mod

None

### Alpha Mod

None

**Comment by Raicuparta** [comment]
Will close this and we can open it again if you decide to submit
