### ISSUE TITLE
OWFixPluginTypesSerialization

### ISSUE THREAD

**Issue by JohnCorby** [ow-mods/ow-mod-db#577]
### Mod uniqueName

JohnCorby.OWFixPluginTypesSerialization

### Mod name

OWFixPluginTypesSerialization

### GitHub repository URL

https://github.com/JohnCorby/OWFixPluginTypesSerialization

### Tags

integration

### Utility mod

Is utility

### Alpha Mod

None

**Comment by MegaPiggy** [comment]
Missing the Patcher.exe in the release zip
