### ISSUE TITLE
Tesseract's Secret

### ISSUE THREAD

**Issue by CantAffordaName** [ow-mods/ow-mod-db#764]
### Your Discord Name

Can't Afford a Name

### Mod uniqueName

CantAffordaName.TesseractsSecret

### Mod name

Tesseract's Secret

### GitHub repository URL

https://github.com/CantAffordaName/CantAffordaName.TesseractsSecret

### Tags

jam, gameplay, story

### Author display name

Can't Afford a Name

### Parent uniqueName

xen.NewHorizons

### Alpha Mod

None

**Comment by JohnCorby** [comment]
whar

**Comment by MegaPiggy** [comment]
???
Why do you keep making an issue for Tesseract? It is already added and there are no changes you've made in these past 2 issues.
