### ISSUE TITLE
madkamel.TidalGrove

### ISSUE THREAD

**Issue by MadKamel** [ow-mods/ow-mod-db#784]
### Your Discord Name

sam_sam_here_i_am

### Mod uniqueName

madkamel.TidalGrove

### Mod name

Tidal Grove

### GitHub repository URL

https://github.com/MadKamel/madkamel.TidalGrove

### Tags

content

### Author display name

MadKamel

### Parent uniqueName

xen.NewHorizons

### Alpha Mod

None

**Comment by MegaPiggy** [comment]
Gone?

**Comment by MadKamel** [comment]
The discord username? Changed. The project? Temporarily on hold. For another month probably.
