### ISSUE TITLE
Little Hearth

### ISSUE THREAD

**Issue by Ceoofurom** [ow-mods/ow-mod-db#806]
### Your Discord Name

ceoofurom

### Mod uniqueName

ceoofurom.littlehearth

### Mod name

Little Hearth

### GitHub repository URL

https://github.com/Ceoofurom/LittleHearth

### Tags

content

### Parent uniqueName

xen.NewHorizons

### DLC Required

None

### Alpha Mod

None

**Comment by MegaPiggy** [comment]
Stuck in purgatory forever 😢

Needs a release that has the mod in a zip file
https://github.com/Ceoofurom/LittleHearth/releases

**Comment by xen-42** [comment]
Closing since their Discord was hacked and we don't know if that applies to their Github as well
