### ISSUE TITLE
Resource Management

### ISSUE THREAD

**Issue by el-piedras** [ow-mods/ow-mod-db#853]
### Your Discord Name

Stonesword_

### Mod uniqueName

Stonesword.resourceManagement

### Mod name

Resource Management

### GitHub repository URL

https://github.com/el-piedras/Resource-Management

### Tags

gameplay, tweaks

### Author display name

Stonesword

### DLC Required

None

### Alpha Mod

None

**Comment by MegaPiggy** [comment]
Needs a zip file of the built mod
